name: Android Build with Android.mk

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK (optional, only if Java components are involved)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install Android NDK
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b  # Stable NDK version as of March 2025
          add-to-path: true

      # Step 4: Install additional build tools (if needed)
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Step 5: Build with ndk-build
      - name: Build with ndk-build
        run: |
          ${ANDROID_NDK}/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=./Android.mk \
            -j$(nproc)

      # Step 6: Archive the build artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl4es-android-lib
          path: |
            libs/**/*.so
            obj/local/**/*.so
